# Excercise
Homeprice price prediction based on area, bedroom and age

In [2]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import matplotlib.pyplot as plt
import math

In [3]:
df = pd.read_csv("C:\\Users\\user\\Documents\\python practice\\Untitled Folder\\hiring.csv")
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [11]:
df = df.rename({"test_score(out of 10)":"test_score","interview_score(out of 10)":"interview_score","salary($)":"salary"}, axis = "columns")

In [12]:
df.experience = df.experience.fillna(0)

In [13]:
df

experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         NaN                7   72000
7        11.0         7.0                8   80000

In [16]:
test_score_median = math.floor(df.test_score.median())
df.test_score = df.test_score.fillna(test_score_median)
df

experience  test_score  interview_score  salary
0         0.0         8.0                9   50000
1         0.0         8.0                6   45000
2         5.0         6.0                7   60000
3         2.0        10.0               10   65000
4         7.0         9.0                6   70000
5         3.0         7.0               10   62000
6        10.0         8.0                7   72000
7        11.0         7.0                8   80000

In [18]:
reg = linear_model.LinearRegression()
reg.fit(df[['experience','test_score','interview_score']],df.salary)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [19]:
reg.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [20]:
reg.intercept_

17737.26346433768

In [21]:
reg.predict([[2,9,6]])

array([53205.96797671])

In [22]:
reg.predict([[12,10,10]])

array([92002.18340611])